server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
    schema: classpath:schema.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Accounts